root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o app.exe cmd/main.go"
bin = "app.exe"
delay = 200

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
